name: gel_annotation-binderized
channels:
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numpy
  - matplotlib
  - pillow
  - pandas-datareader>=0.5.0
  - plotly
  - plotly plotly-orca
  - psutil
  - pip
  - pip:
    - opencv-python-headless
