#!/bin/bash

# Download orca AppImage, extract it, and make it executable under xvfb
wget https://github.com/plotly/orca/releases/download/v1.1.1/orca-1.1.1-x86_64.AppImage -P /home
chmod 777 /home/orca-1.1.1-x86_64.AppImage 

# To avoid the need for FUSE, extract the AppImage into a directory (name squashfs-root by default)
cd /home && /home/orca-1.1.1-x86_64.AppImage --appimage-extract
printf '#!/bin/bash \nxvfb-run --auto-servernum --server-args "-screen 0 640x480x24" /home/squashfs-root/app/orca "$@"' > /usr/bin/orca
chmod 777 /usr/bin/orca
chmod -R 777 /home/squashfs-root/